# Generated by Django 5.1.4 on 2025-01-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
